[build]
  command = "npm run build"
  publish = ".next"  # This is correct for non-export builds

[[headers]]
  for = "/*"
    [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[[headers]]
  for = "/_next/image/*"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"